version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3307:3307"

  app:
    build: .
    volumes:
      - .:/app_name
    ports:
      - "3001:3001"
    depends_on:
      - db
